# ── Build stage ───────────────────────────────────────────────
FROM golang:1.22-alpine AS builder

RUN apk add --no-cache git ca-certificates tzdata

WORKDIR /app

# Copy dependency manifests first for layer caching.
# go.sum is committed to the repo — generated by running:
#   go mod tidy
# on a machine with internet access (see README).
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

# 1. Formatting check — fails build if any file is not gofmt-clean
RUN test -z "$(gofmt -l ./...)" || \
    (echo "gofmt: unformatted files:"; gofmt -l ./...; exit 1)

# 2. Unit tests — fails build if any test fails
RUN go test -count=1 ./...

# 3. Compile — fails build if there are compile errors
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-s -w" -o /app/server ./cmd/api

# ── Runtime stage (minimal scratch image) ────────────────────
FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /usr/share/zoneinfo                 /usr/share/zoneinfo
COPY --from=builder /app/server                         /server

EXPOSE 8080

ENTRYPOINT ["/server"]
