lines = [
"package store",
"",
"import (",
'\t"context"',
'\t"encoding/json"',
'\t"fmt"',
"",
'\t"github.com/google/uuid"',
'\t"github.com/jackc/pgx/v5"',
'\t"golang.org/x/crypto/bcrypt"',
'\t"github.com/quran-school/api/internal/model"',
")",
"",
"func ListRoles(ctx context.Context, tx pgx.Tx) ([]model.SchoolRole, error) {",
"\tq := `SELECT id,school_id,name,slug,permissions,is_system,created_at FROM school_roles ORDER BY name`",
"\trows, err := tx.Query(ctx, q)",
"\tif err != nil { return nil, fmt.Errorf(\"store.ListRoles: %w\", err) }",
"\tdefer rows.Close()",
"\tvar list []model.SchoolRole",
"\tfor rows.Next() {",
"\t\tvar r model.SchoolRole",
"\t\tif err := rows.Scan(&r.ID,&r.SchoolID,&r.Name,&r.Slug,&r.Permissions,&r.IsSystem,&r.CreatedAt); err != nil { return nil, err }",
"\t\tlist = append(list, r)",
"\t}",
"\treturn list, nil",
"}",
"",
"func UpdateRolePermissions(ctx context.Context, tx pgx.Tx, id uuid.UUID, perms json.RawMessage) (*model.SchoolRole, error) {",
"\tvar r model.SchoolRole",
"\tq := `UPDATE school_roles SET permissions=$2 WHERE id=$1 RETURNING id,school_id,name,slug,permissions,is_system,created_at`",
"\terr := tx.QueryRow(ctx, q, id, perms).Scan(&r.ID,&r.SchoolID,&r.Name,&r.Slug,&r.Permissions,&r.IsSystem,&r.CreatedAt)",
"\tif err != nil { return nil, fmt.Errorf(\"store.UpdateRolePermissions: %w\", err) }",
"\treturn &r, nil",
"}",
"",
"func ListStaff(ctx context.Context, tx pgx.Tx) ([]model.SchoolStaff, error) {",
"\tq := `SELECT s.id,s.school_id,s.role_id,r.name,r.slug,s.full_name,s.username,s.password_plain,s.is_active,s.created_at,s.updated_at FROM school_staff s JOIN school_roles r ON r.id=s.role_id ORDER BY s.full_name`",
"\trows, err := tx.Query(ctx, q)",
"\tif err != nil { return nil, fmt.Errorf(\"store.ListStaff: %w\", err) }",
"\tdefer rows.Close()",
"\tvar list []model.SchoolStaff",
"\tfor rows.Next() {",
"\t\tvar s model.SchoolStaff",
"\t\tif err := rows.Scan(&s.ID,&s.SchoolID,&s.RoleID,&s.RoleName,&s.RoleSlug,&s.FullName,&s.Username,&s.PasswordPlain,&s.IsActive,&s.CreatedAt,&s.UpdatedAt); err != nil { return nil, err }",
"\t\tlist = append(list, s)",
"\t}",
"\treturn list, nil",
"}",
"",
"func CreateStaff(ctx context.Context, tx pgx.Tx, schoolID uuid.UUID, r *model.CreateStaffRequest) (*model.SchoolStaff, error) {",
"\thash, err := bcrypt.GenerateFromPassword([]byte(r.Password), bcrypt.DefaultCost)",
"\tif err != nil { return nil, err }",
"\troleID, err := uuid.Parse(r.RoleID)",
"\tif err != nil { return nil, fmt.Errorf(\"invalid role_id: %w\", err) }",
"\tvar s model.SchoolStaff",
"\tq := `INSERT INTO school_staff (school_id,role_id,full_name,username,password_hash,password_plain,is_active) VALUES ($1,$2,$3,$4,$5,$6,true) RETURNING id,school_id,role_id,full_name,username,password_plain,is_active,created_at,updated_at`",
"\terr = tx.QueryRow(ctx, q, schoolID, roleID, r.FullName, r.Username, string(hash), r.PasswordPlain).Scan(&s.ID,&s.SchoolID,&s.RoleID,&s.FullName,&s.Username,&s.PasswordPlain,&s.IsActive,&s.CreatedAt,&s.UpdatedAt)",
"\tif err != nil { return nil, fmt.Errorf(\"store.CreateStaff: %w\", err) }",
"\treturn &s, nil",
"}",
"",
"func UpdateStaff(ctx context.Context, tx pgx.Tx, id uuid.UUID, r *model.UpdateStaffRequest) (*model.SchoolStaff, error) {",
'\tsets := "updated_at=now()"',
"\targs := []any{id}",
"\tn := 2",
'\tif r.FullName != nil      { sets += fmt.Sprintf(",full_name=$%d", n);      args = append(args, *r.FullName);      n++ }',
'\tif r.Username != nil      { sets += fmt.Sprintf(",username=$%d", n);        args = append(args, *r.Username);      n++ }',
'\tif r.IsActive != nil      { sets += fmt.Sprintf(",is_active=$%d", n);       args = append(args, *r.IsActive);      n++ }',
'\tif r.PasswordPlain != nil { sets += fmt.Sprintf(",password_plain=$%d", n);  args = append(args, *r.PasswordPlain); n++ }',
"\tif r.Password != nil {",
"\t\thash, _ := bcrypt.GenerateFromPassword([]byte(*r.Password), bcrypt.DefaultCost)",
'\t\tsets += fmt.Sprintf(",password_hash=$%d", n); args = append(args, string(hash)); n++',
"\t}",
"\tif r.RoleID != nil {",
"\t\trid, _ := uuid.Parse(*r.RoleID)",
'\t\tsets += fmt.Sprintf(",role_id=$%d", n); args = append(args, rid); n++',
"\t}",
"\tvar s model.SchoolStaff",
'\tq := fmt.Sprintf("UPDATE school_staff SET %s WHERE id=$1 RETURNING id,school_id,role_id,full_name,username,password_plain,is_active,created_at,updated_at", sets)',
"\terr := tx.QueryRow(ctx, q, args...).Scan(&s.ID,&s.SchoolID,&s.RoleID,&s.FullName,&s.Username,&s.PasswordPlain,&s.IsActive,&s.CreatedAt,&s.UpdatedAt)",
"\tif err != nil { return nil, fmt.Errorf(\"store.UpdateStaff: %w\", err) }",
"\treturn &s, nil",
"}",
"",
"func GetSettings(ctx context.Context, tx pgx.Tx, schoolID uuid.UUID) (*model.SchoolSettings, error) {",
"\tvar s model.SchoolSettings",
"\tq := `SELECT school_id,currency,language,timezone,date_format,logo_url,address,phone,email,updated_at FROM school_settings WHERE school_id=$1`",
"\terr := tx.QueryRow(ctx, q, schoolID).Scan(&s.SchoolID,&s.Currency,&s.Language,&s.Timezone,&s.DateFormat,&s.LogoURL,&s.Address,&s.Phone,&s.Email,&s.UpdatedAt)",
"\tif err == pgx.ErrNoRows { return &model.SchoolSettings{SchoolID:schoolID,Currency:\"SAR\",Language:\"ar\",Timezone:\"Asia/Riyadh\",DateFormat:\"hijri\"}, nil }",
"\tif err != nil { return nil, fmt.Errorf(\"store.GetSettings: %w\", err) }",
"\treturn &s, nil",
"}",
"",
"func UpsertSettings(ctx context.Context, tx pgx.Tx, schoolID uuid.UUID, r *model.UpdateSettingsRequest) (*model.SchoolSettings, error) {",
"\tvar s model.SchoolSettings",
"\tq := `INSERT INTO school_settings (school_id,currency,language,timezone,date_format,logo_url,address,phone,email) VALUES ($1,COALESCE($2,'SAR'),COALESCE($3,'ar'),COALESCE($4,'Asia/Riyadh'),COALESCE($5,'hijri'),$6,$7,$8,$9) ON CONFLICT (school_id) DO UPDATE SET currency=COALESCE(EXCLUDED.currency,school_settings.currency),language=COALESCE(EXCLUDED.language,school_settings.language),timezone=COALESCE(EXCLUDED.timezone,school_settings.timezone),date_format=COALESCE(EXCLUDED.date_format,school_settings.date_format),logo_url=COALESCE(EXCLUDED.logo_url,school_settings.logo_url),address=COALESCE(EXCLUDED.address,school_settings.address),phone=COALESCE(EXCLUDED.phone,school_settings.phone),email=COALESCE(EXCLUDED.email,school_settings.email),updated_at=now() RETURNING school_id,currency,language,timezone,date_format,logo_url,address,phone,email,updated_at`",
"\terr := tx.QueryRow(ctx, q, schoolID,r.Currency,r.Language,r.Timezone,r.DateFormat,r.LogoURL,r.Address,r.Phone,r.Email).Scan(&s.SchoolID,&s.Currency,&s.Language,&s.Timezone,&s.DateFormat,&s.LogoURL,&s.Address,&s.Phone,&s.Email,&s.UpdatedAt)",
"\tif err != nil { return nil, fmt.Errorf(\"store.UpsertSettings: %w\", err) }",
"\treturn &s, nil",
"}",
]
with open("internal/store/settings.go", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print("OK:", len(lines), "lines")
